import React from 'react';
import { createRoot } from 'react-dom/client';
import { AppRegistry } from 'react-native';
import App from './App';

// Register the application
AppRegistry.registerComponent('App', () => App);

// Get the application element and the style element for web
// Fixed: Cast AppRegistry to any to access getApplication which is available in react-native-web but missing in standard React Native types.
const { element, getStyleElement } = (AppRegistry as any).getApplication('App');

const rootTag = document.getElementById('root');
if (rootTag) {
  const root = createRoot(rootTag);
  root.render(
    <React.Fragment>
      {/* Explicitly inject the CSS generated by StyleSheet.create */}
      {getStyleElement()}
      {element}
    </React.Fragment>
  );
}
